### ISSUE TITLE
NoClassDefFound com/google/protobuf/RuntimeVersion$RuntimeDomain

### ISSUE THREAD

**Issue by harti2006** [authzed/authzed-java#103]
The latest release [v0.11.0](https://github.com/authzed/authzed-java/releases/tag/v0.11.0), bumped the dependency on Protobuf from 3.25 to 4.27, which causes some compatibility issues in my project that uses the Authzed SDK.

Protobuf introduced some breaking changes in [version 4.26](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0).

My project still needs to work with Protobuf 3.25, because it has dependencies on other libraries, that have been compiled with this version of Protobuf. It turns out, that it is not possible to use two libraries, one compiled with Protobuf v3.25 and the other with v4.26 in the same project. Doing so results in runtime errors like:

> NoClassDefFound com/google/protobuf/RuntimeVersion$RuntimeDomain

[Protobuf version 4.28](https://github.com/protocolbuffers/protobuf/releases/tag/v28.0) tries to bring back compatibility with version 3.25, but I cannot yet confirm this
> Binary compatibility shims for GeneratedMessageV3, SingleFieldBuilderV3, RepeatedFieldBuilderV3, and their nested classes to restore binary compatibility with <=v3.x.x generated code built against v3.x.x prior to v4.26.0 breaking release.

Could you please either revert the [Protobuf upgrade](https://github.com/authzed/authzed-java/commit/59a2826d16c263be473687650324e572022f24f5) back to 3.25? Alternatively, moving forward to 4.28 might also solve the issue, but I have to test that first.

**Comment by tstirrat15** [comment]
If you have the means, would you be willing to test 4.28? I'd rather move the library forward if possible.

Alternatively, can you pin to 0.10.0? The only change with 0.11.0 is bumping the protobuf version - there shouldn't be big functionality changes.

What you're describing is something that I've seen in other clients as well - it seems that the protobuf project assumes that rather than consuming libraries that have been generated with protobuf, you would consume the proto directly and do your own generation process. If that dependency conflict becomes too sticky, that may be a way to proceed.

**Comment by tstirrat15** [comment]
Sounds good! I'll get a PR together for that.

**Comment by tstirrat15** [comment]
This is going out in v0.11.1. When [this action](https://github.com/authzed/authzed-java/actions/runs/10815589287) completes it should be available on maven.

**Comment by harti2006** [comment]
Wonderful. v0.11.1 works fine for me.
Thanks a lot for providing this fix so quickly ☺️

**Comment by tstirrat15** [comment]
Sure thing!

**Comment by amihaiemil** [comment]
@tstirrat15 I am unfortunately still getting the same error, even though I am using v1.0.0. Looking inside the pom.xml of v1.0.0, I see it depends on:

```xml
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-protobuf</artifactId>
    <version>1.66.0</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>4.28.2</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-stub</artifactId>
    <version>1.66.0</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-netty-shaded</artifactId>
    <version>1.66.0</version>
    <scope>runtime</scope>
</dependency>
```

According to your discussion, protobuf-java 4.28.2 should fix the problem, but it doesn't? Any ideas? :D

**Comment by harti2006** [comment]
Not sure if it's a big help, but you can make the dependency tree more verbose like this:
```sh
mvn dependency:tree -Dverbose=true
```

It will show you all transitive dependencies, conflicts and which versions have been picked in the end.

@amihaiemil I can also see that different versions of grpc are used in your project (1.68.0 and 1.66.0). Not sure if this is a problem at all, but you might be able to get better control by using BOMs:
```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-bom</artifactId>
            <version>1.68.1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-bom</artifactId>
            <version>4.28.3</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by amihaiemil** [comment]
@tstirrat15 @harti2006 I cleaned the maven cache, I also checked the dependency versions (tried multiple versions from each), but still the same behaviour. 

Could it maybe have to do with the fact that I am under MacOs (Sequoia v15.0.1)?

**Comment by tstirrat15** [comment]
@amihaiemil that shouldn't make a difference I don't think.

**Comment by amihaiemil** [comment]
@tstirrat15 Other colleagues under Windows say it works for them. I'm still looking for a solution :(

**Comment by amihaiemil** [comment]
@harti2006 It was indeed a conflict problem with an older version of protobuf-java. According to my pom.xml this should have been added in the final package:

```xml
<dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>4.28.2</version>
      <scope>runtime</scope>
</dependency>
```
However, dependency:tree verbose revelead that actually version 3.19.4 was coming transitively from a whole other dependency... 

Many thanks for your help!

**Comment by tstirrat15** [comment]
Yeah, that's one of the frustrating things about the protobuf ecosystem - there seems to be an implicit assumption that the way you'd use protobuf is to collect all of the protobuf for your various services in one place and run the code generation once, such that every generated client is using the same version of protobuf. Having multiple generated libraries in the same project from different sources can violate that assumption.
