### ISSUE TITLE
BearerToken not present in com.authzed.api maven import

### ISSUE THREAD

**Issue by calaracey** [authzed/authzed-java#21]
Hi, thanks for making this great repo. 

The readme instructions say to add the following maven dependency:

```
<dependency>
  <groupId>com.authzed.api</groupId>
  <artifactId>authzed</artifactId>
  <version>0.0.1</version>
</dependency>
```
and to import the following libraries:

```
import com.authzed.api.v0.ACLServiceGrpc;
import com.authzed.grpcutil.BearerToken;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
```
As far as I can tell, `com.authzed.grpcutil.BearerToken` is not present in the `com.authzed.api` jar so the only option is to get the [source code](https://github.com/authzed/authzed-java/blob/a66b72129fc769315b0c66c6fb6fdbe06c4ad3b1/src/main/java/com/authzed/grpcutil/BearerToken.java) and add it to the project manually.

If I have missed something please let me know, but otherwise I think it would be a lot more convenient if `BearerToken` was included in either `com.authzed.api` or its own maven dependency. I also looked for a `com.authzed.grpcutil` on maven but could not find anything.

**Comment by samkim** [comment]
Thanks for filing an issue. The BearerToken util was added in v0.0.2 so that's why it's missing. Update your maven dependency to v0.1.0 and you should be good to go. We'll update the readme to reflect this as well.
