### ISSUE TITLE
Generated LookupSubjectsRequest missing optional_concrete_limit in v0.5.0

### ISSUE THREAD

**Issue by andresanches** [authzed/authzed-java#48]
[LookupSubjectsRequest] in the v1 api schema describes the field `optional_concrete_limit` that was not included in the generated java classes when [v0.5.0] was published.

Interestingly, the similarly named `optional_limit` field in the [LookupResourcesRequest] counterpart was included in the respective generated code.

I've attached [PermissionService.zip](https://github.com/authzed/authzed-java/files/11896618/PermissionService.zip) with the generated code in case it helps.

[LookupSubjectsRequest]: https://buf.build/authzed/api/docs/main:authzed.api.v1#authzed.api.v1.PermissionsService.LookupSubjects
[v0.5.0]: https://github.com/authzed/authzed-java/releases/tag/0.5.0
[LookupResourcesRequest]: https://buf.build/authzed/api/docs/main:authzed.api.v1#authzed.api.v1.LookupResourcesRequest

**Comment by andresanches** [comment]
Understood, thanks the quick response! Feel free to either close this issue or keep it open until the feature is released so others know this is a known issue.

**Comment by jzelinskie** [comment]
https://github.com/authzed/api/issues/71
