### ISSUE TITLE
Ignore "OuterClass" suffix in the generated java classes for better readability

### ISSUE THREAD

**Issue by Sriram-Saranathan** [authzed/authzed-java#80]
Some of the generated classes include the "OuterClass" suffix in their names. Please refrain from generating class names with that suffix for better readability.

<img width="431" alt="Screenshot 2024-03-25 at 1 09 04 PM" src="https://github.com/authzed/authzed-java/assets/63400498/ec8dbab3-5658-4da7-b216-313cccf7223b">

**Comment by vroldanbet** [comment]
@Sriram-Saranathan this will go out in the next release
